libraryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from library import views as library_views
from library.views import *

from django.conf.urls.static import static
from django.conf import settings

from library import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', library_views.home, name='home'),
    path('about/', library_views.about),
    path('book_description/<int:book_id>/', book_details, name='book_description'),
    path('book_details/<int:book_id>/', book_details, name='book_details'),  # Nueva URL para book_details
    path('change_availability/<int:book_id>/', views.change_availability, name='change_availability'),
    path('reserve_book/<int:book_id>/', views.reserve_book, name='reserve_book'),
    path('change_real_availability/<int:book_id>/', views.change_real_availability, name='change_real_availability'),
    path('verify_availability/<int:book_id>/', views.verify_availability, name='verify_availability'),
    path('adminrent/<int:book_id>/', views.adminrent, name='adminrent'),
    path('rate-book/', views.rate_book, name='rate_book'),
    path('submit_review/', views.submit_review, name='submit_review'),
    path('form/', views.add_book, name='add_book'),
    path('mainapp/', include('mainapp.urls')),
    path('book_history/', views.book_history, name='book_history'),
    path('rent_name/<int:book_id>/', library_views.rent_name, name='rent_name'),  # URL para procesar el alquiler del libro
    path('book_description/<int:book_id>/<str:username>/', views.confirm_rental, name='confirm_rental'),
    path('cancel_rent/<int:book_id>/', views.cancel_rent, name='cancel_rent'),
    path('register_users/', views.register_user, name='register_user'),
    path('edit_users/', views.edit_user, name='edit_user'),
    path('editar_usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('delete_users/', views.delete_user, name='delete_user'),
    path('eliminar_usuario/<int:user_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('edit_book/<int:book_id>/', views.edit_book, name='edit_book'),
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    # Password change
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    # reset password 
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    # User registration
    path('register/', views.register, name='register'),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField(default='Description not available')
    image = models.ImageField(upload_to='library/images/')
    available = models.BooleanField(default=True)
    availability = models.DateField(null=True, blank=True)
    real_available = models.BooleanField(default=True)
    real_availability = models.DateField(null=True, blank=True)
    reserved = models.BooleanField(default=False)
    reserved_date = models.DateField(null=True, blank=True)
    reserved_by = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        related_name='books_reserved'
    )
    rented_by = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        related_name='books_rented'
    )
    total_ratings = models.IntegerField(default=0)
    sum_ratings = models.IntegerField(default=0)
    rating_average = models.DecimalField(max_digits=3, decimal_places=2, default=0)

class BookDetails(models.Model):
    book = models.OneToOneField(Book, on_delete=models.CASCADE, related_name='bookdetails', default=None)
    isbn = models.CharField(max_length=13,default='N/A')
    genre = models.CharField(max_length=100,default='N/A')
    subject = models.CharField(max_length=100, default='N/A')
    publisher = models.CharField(max_length=100, default='N/A')

#Esta función crea automáticamente un objeto de BookHistory asociado cuando se crea un nuevo usuario.
def create_bookdetails_book(sender, instance, created, **kwargs):

    if created:
         BookDetails.objects.create(book=instance)

#Esta función guarda automáticamente el historial de libros después de que se guarda el objeto User.
def save_bookdetails_book(sender, instance, **kwargs): 
    instance.bookdetails.save()

post_save.connect(create_bookdetails_book, sender=Book)
post_save.connect(save_bookdetails_book, sender=Book)

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)  # Hacer el campo anulable
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    
class Rating(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    value = models.IntegerField()

    class Meta:
        unique_together = ('book', 'user')

class BookHistory(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='bookhistory', default=None)
    rented_books = models.ManyToManyField(Book, blank=True)

#Esta función crea automáticamente un objeto de BookHistory asociado cuando se crea un nuevo usuario.
def create_bookhistory_user(sender, instance, created, **kwargs):

    if created:
         BookHistory.objects.create(user=instance)

#Esta función guarda automáticamente el historial de libros después de que se guarda el objeto User.
def save_bookhistory_user(sender, instance, **kwargs): 
    instance.bookhistory.save()

# Estas 2 líneas de código conectan las funciones a las señales post_save para el modelo User.
# Cuando se crea o actualiza un objeto User, estas funciones se ejecutan automáticamente.

post_save.connect(create_bookhistory_user, sender=User)
post_save.connect(save_bookhistory_user, sender=User)

library/forms.py
from django import forms
from .models import Book, BookDetails

class LibroForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'image', 'reserved_date', 'reserved','rating_average']

class DetailsForm(forms.ModelForm):
    class Meta:
        model = BookDetails
        fields = ['isbn', 'publisher', 'genre', 'subject']

library/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from .models import Book, Review, Rating, BookHistory, BookDetails
from django.urls import reverse
import datetime
from datetime import date, timedelta
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from .forms import LibroForm, DetailsForm
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms
from .models import User
from django.contrib.auth import login, authenticate
from django.template import loader

from django.contrib.auth.forms import UserCreationForm

from .services import LibraryService

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='First name')
    last_name = forms.CharField(max_length=30, required=True, help_text='Last name')
    email = forms.EmailField(max_length=254, required=True, help_text='Email address')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

def home(request):
    cancel_reservation_automatic(request)
    check_rented(request)
    
    # Obtiene el término de búsqueda y la opción de ordenación desde la solicitud
    searchTerm = request.GET.get('searchBook')
    sort_option = request.GET.get('sort')
    
    # Filtra los libros según el término de búsqueda si existe
    if searchTerm and searchTerm != 'None':
        books = Book.objects.filter(title__icontains=searchTerm)
    else:
        books = Book.objects.all()
    
    # Aplica la ordenación según la opción seleccionada
    if sort_option == 'asc':
        books = books.order_by('rating_average')
    elif sort_option == 'desc':
        books = books.order_by('-rating_average')
    elif sort_option == 'genre':
        books = books.order_by('bookdetails__genre')
    elif sort_option == 'subject':
        books = books.order_by('bookdetails__subject')
    
    # Renderiza la plantilla con los libros filtrados y ordenados, y los parámetros de búsqueda y ordenación
    return render(request, 'home.html', {'books': books, 'searchTerm': searchTerm, 'sort_option': sort_option})


@login_required
def rate_book(request):
    cancel_reservation_automatic(request)
    check_rented(request)
    if request.method == 'POST':
        book_id = request.POST.get('book_id')
        rating = request.POST.get('rating')
        
        if not rating:
            return HttpResponseBadRequest("No se ha proporcionado una calificación.")
        
        rating = int(rating)
        
        book = get_object_or_404(Book, id=book_id)
        user = request.user
        
        # Verificar si el usuario ya ha dejado un rating para este libro
        existing_rating = Rating.objects.filter(book=book, user=user).exists()
        if existing_rating:
            return HttpResponseBadRequest("Ya has dejado un rating para este libro.")
        
        # Crear el rating
        Rating.objects.create(book=book, user=user, value=rating)
        
        # Calcular el rating promedio del libro
        ratings = Rating.objects.filter(book=book)
        total_ratings = ratings.count()
        sum_ratings = sum(rating.value for rating in ratings)
        book.rating_average = sum_ratings / total_ratings
        book.save()
        
    return redirect('home')
 

@login_required
def submit_review(request):
    cancel_reservation_automatic(request)
    check_rented(request)
    if request.method == 'POST':
        book_id = request.POST.get('book_id')
        review_text = request.POST.get('reviewText')
        book = Book.objects.get(id=book_id)
        # Aquí asegúrate de asignar correctamente el usuario al crear la instancia de Review
        Review.objects.create(book=book, user=request.user, text=review_text)
        # Redirige a la página de descripción del libro con el ancla del comentario
        return HttpResponseRedirect(reverse('book_details', args=(book_id,)) + '#reviews')
    else:
        return redirect('home')

def about(request):
    cancel_reservation_automatic(request)
    check_rented(request)
    return render(request, 'about.html')

def book_details(request, book_id):
    cancel_reservation_automatic(request)
    check_rented(request)
    book = get_object_or_404(Book, pk=book_id)
    details = BookDetails.objects.get(book = book)
    reviews = Review.objects.filter(book=book)
    return render(request, 'book_description.html', {'book': book,'details':details, 'reviews': reviews})


"""def book_description(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'book_description.html', {'book': book})"""

def adminrent(request, book_id):
    cancel_reservation_automatic(request)
    check_rented(request)
    book = get_object_or_404(Book, pk=book_id)
    
    return render(request, 'adminrent.html', {'book': book})


def change_availability(request, book_id):
    cancel_reservation_automatic(request)
    check_rented(request)
    book = get_object_or_404(Book, pk=book_id)
    
    # Cambiar el estado de disponibilidad
    if book.available:
        book.available = False
        book.availability = datetime.date.today() + datetime.timedelta(days=31)  # Establecer la disponibilidad en 31 días desde hoy
    else:
        book.available = True
        book.availability = None
    
    book.save()
    
    # Redirigir a la página de descripción del libro actualizado
    return HttpResponseRedirect(reverse('book_details', args=(book_id,)))

"""
@login_required
def reserve_book(request, book_id):
    cancel_reservation_automatic(request)
    check_rented(request)
    book = get_object_or_404(Book, pk=book_id)
    user = request.user
    
    # Verificar si el libro está reservado y si el usuario actual realizó esa reserva
    if book.reserved and book.reserved_by != user and not user.is_staff:
        # Mostrar un mensaje de error en la misma página
        messages.error(request, "You are not authorized to cancel this reservation.")
        # Obtener las reseñas del libro para pasarlas a la plantilla
        reviews = Review.objects.filter(book=book)
        # Renderizar la página de descripción del libro actualizada con el mensaje de error y las reseñas
        return render(request, 'book_description.html', {'book': book, 'reviews': reviews, 'error_message': "You are not authorized to cancel this reservation."})
    
    # Cambiar el estado de reserva
    if book.reserved:
        book.reserved = False
        book.reserved_date = None
        book.reserved_by = None  # Limpiar el campo del usuario que reservó
    else:
        book.reserved = True
        book.reserved_date = datetime.date.today() + datetime.timedelta(days=7)  # Establecer la fecha de reserva en 7 días desde hoy
        book.reserved_by = user  # Establecer el usuario actual como el que reservó
    
    book.save()
    
    # Redirigir a la página de descripción del libro actualizado
    return HttpResponseRedirect(reverse('book_details', args=(book_id,)))
"""

@login_required
def reserve_book(request, book_id, library_service=LibraryService()):
    # Usar los métodos a través de la interfaz
    library_service.cancel_reservation_automatic()
    library_service.check_rented()

    book = get_object_or_404(Book, pk=book_id)
    user = request.user

    if book.reserved and book.reserved_by != user and not user.is_staff:
        reviews = Review.objects.filter(book=book)
        messages.error(request, "You are not authorized to cancel this reservation.")
        return render(request, 'book_description.html', {
            'book': book,
            'reviews': reviews,
            'error_message': "You are not authorized to cancel this reservation."
        })

    if book.reserved:
        book.reserved = False
        book.reserved_date = None
        book.reserved_by = None
    else:
        book.reserved = True
        book.reserved_date = datetime.today().date() + timedelta(days=7)
        book.reserved_by = user

    book.save()

    return HttpResponseRedirect(reverse('book_details', args=(book_id,)))



def change_real_availability(request, book_id):
    cancel_reservation_automatic(request)
    check_rented(request)
    book = get_object_or_404(Book, pk=book_id)
    
    if book.real_available:
        book.real_available = False
        book.real_availability = datetime.date.today() + datetime.timedelta(days=14)
    else:
        book.real_available = True
        book.real_availability = None 
        
    book.save()
    
    return HttpResponseRedirect(reverse('book_details', args=(book_id,)))

def verify_availability(request, book_id):
    cancel_reservation_automatic(request)
    check_rented(request)
    book = get_object_or_404(Book, pk=book_id)
    
    if book.real_available and not book.reserved:
        book.available = True
        book.availability = None
    elif book.real_available and book.reserved:
        book.available = False
        book.availability = book.reserved_date + datetime.timedelta(days=14)
    else:
        book.available = False
        book.availability = book.real_availability
        
    book.save()
    
    # Redirigir a la página de descripción del libro actualizado
    return HttpResponseRedirect(reverse('book_details', args=(book_id,)))

def add_book(request):
    cancel_reservation_automatic(request)
    check_rented(request)
    if request.method == 'POST':
        form = LibroForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save()
            book_id = book.id

library/templates/about.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bibliatica</title>
</head>
<body>
    <h1>Bibliatica</h1>
    <p>Welcome to our library. We store information about every book, including availability, to accelerate and facilitate the process of renting books. No more unnecessary trips to the library if the book you need is not available.</p>
    <h2>Features:</h2>
    <ul>
        <li>Search for books by title
            {% comment %} , author, or genre {% endcomment %}
            .</li>
        <li>Check availability status before visiting the library.</li>
        {% comment %} <li>Rent books online for convenient pickup.</li> {% endcomment %}
    </ul>
    <h2>How it Works:</h2>
    <ol>
        <li>Browse our catalog or use the search feature to find the book you want.</li>
        <li>Check the availability status displayed next to each book.</li>
        {% comment %} <li>If the book is available, you can rent it online.</li> {% endcomment %}
        <li>Visit the library to pick up your reserved books.</li>
    </ol>
    <footer>
        <p>Contact us for more information or assistance.</p>
    </footer>
</body>
</html>
{% endblock content %}

library/templates/adminrent.html
{% extends "base.html" %}
{% block content %}



















{% endblock content %}

library/templates/book_description.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- Descripción del Libro -->
        <div class="col-md-4">
            <div class="card h-100">
                <img src="{{ book.image.url }}" class="card-img-top img-thumbnail mb-3" alt="Book Cover">
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                <a href="{% url 'edit_book' book.id %}" class="btn btn-info">Edit</a>
                <a href="{% url 'delete_book' book.id %}" class="btn btn-danger">Delete</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="col-md-8">
            <div class="card h-100" >
                <div class="card-body" style="max-height: 500px; overflow-y: auto;">
                    <h2 class="card-title" style="text-align: center;">{{ book.title }}</h2>
                    <h2 class="card-title" style="text-align: center;">{{ book.author }}</h2>
                    <h3 class="card-subtitle mb-2 text-muted" style="text-align: center;">ISBN : {{details.isbn}}</h3>
                    <h3 class="card-subtitle mb-2 text-muted" style="text-align: center;">Publisher : {{details.publisher}}</h3>
                    <h3 class="card-subtitle mb-2 text-muted" style="text-align: center;">Genre : {{details.genre}}</h3>
                    <h3 class="card-subtitle mb-2 text-muted" style="text-align: center;">Subject : {{details.subject}}</h3>
                    <p class="card-text">{{ book.description }}</p>
                </div>
            </div>
        </div>

        <!-- Comentarios y Reseñas -->
        <div class="col-md-12 mt-4">
            <div class="card h-100">
                <div class="card-body d-flex flex-column">
                    <h2 class="card-title">Reviews</h2>
                    <!-- Reviews -->
                    <div class="reviews flex-grow-1" style="max-height: 300px; overflow-y: auto;">
                        {% if reviews %}
                            {% for review in reviews %}
                                <div class="card mb-3">
                                    <div class="card-body">
                                        <p class="card-text">{{ review.text }}</p>
                                        <p class="card-subtitle text-muted">By {{ review.user.username }} on {{ review.created_at }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <p class="card-text">No reviews yet.</p>
                        {% endif %}
                    </div>
                    <!-- Leave a Review Form -->
                    <div class="card mt-4">
                        <div class="card-body">
                            <h3 class="card-title">Leave a Review</h3>
                            {% if user.is_authenticated %}
                                <form method="POST" action="{% url 'submit_review' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="book_id" value="{{ book.id }}">
                                    <div class="mb-3">
                                        <label for="reviewText" class="form-label">Your Review:</label>
                                        <textarea class="form-control" name="reviewText" id="reviewText" rows="3" style="resize: none;"></textarea>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Submit Review</button>
                                </form>
                            {% else %}
                                <p class="card-text">Please <a href="{% url 'login' %}">log in</a> to leave a comment.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Reservar Libro -->
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card h-100">
                <div class="card-body text-center">
                    {% if user.is_authenticated %}
                        
                        {% if book.real_available and not book.reserved %}
                            <p class="card-text">Available</p>
                            <a href="{% url 'reserve_book' book.id %}" class="btn btn-info">Reserve</a>
                        {% elif book.real_available and book.reserved %}
                            <p class="card-text">Reserved until <span>{{ book.reserved_date }}</span></p>
                            <a href="{% url 'reserve_book' book.id %}" class="btn btn-info">Cancel reservation</a>
                        {% elif book.real_available and book.reserved %}
                            <p class="card-text">Reserved until <span>{{ book.reserved_date }}</span></p>
                        {% else %}
                            <p class="card-text">Rented until <span>{{ book.real_availability }}</span></p>
                        {% endif %}
                    {% else %}
                        <p class="card-text">Please <a href="{% url 'login' %}">log in</a> to reserve this book</p>
                    {% endif %}
                    <br><br><br>
                    {% if user.is_staff %}
                        {% if book.real_available %}
                            <a href="{% url 'rent_name' book.id %}" class="btn btn-info">Rent</a>
                        {% else %}
                            <a href="{% url 'cancel_rent' book.id %}" class="btn btn-info">Cancel Rent</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <!-- Espacio para mostrar el mensaje de error -->
    {% if error_message %}
        <div class="alert alert-danger mt-4" role="alert">
            {{ error_message }}
        </div>
    {% endif %}
</div>
{% endblock content %}

library/templates/delete_users.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Eliminar Usuarios</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Username</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <a href="{% url 'eliminar_usuario' user.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

library/templates/edit_book.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data" class="profile-form">
        {% csrf_token %}
        <div class="form-group">
            {{ form_book.title.label_tag }}
            <input type="text" class="form-control" id="id_title" name="title" required value="{{book.title}}">
        </div>
        <div class="form-group">
            {{ form_book.author.label_tag }}
            <input type="text" class="form-control" id="id_author" name="author" required value="{{book.author}}">
        </div>
        <div class="form-group">
            {{ form_details.isbn.label_tag }}
            <input type="text" class="form-control" id="id_isbn" name="isbn" required value="{{bookdetails.isbn}}">   
        </div>
        <div class="form-group">
            {{ form_details.genre.label_tag }}
            <input type="text" class="form-control" id="id_genre" name="genre" required value="{{bookdetails.genre}}">   
        </div>
        <div class="form-group">
            {{ form_details.subject.label_tag }}
            <input type="text" class="form-control" id="id_subject" name="subject" required value="{{bookdetails.subject}}">   
        </div>
        <div class="form-group">
            {{ form_details.publisher.label_tag }}
            <input type="text" class="form-control" id="id_publisher" name="publisher" required value="{{bookdetails.publisher}}">   
        </div>
        <div class="form-group">
            {{ form_book.description.label_tag }}
            <textarea class="form-control" id="id_description" name="description" rows="4" cols="50" required>{{ book.description }}</textarea>
        </div>
        <div class="form-group">
            {{ form_book.image.label_tag }}
            <input type="file" class="form-control-file" id="id_image" name="image" accept="image/*" >
        </div>
        <div class="form-group">
            {{ form_book.reserved_date.label_tag }}
            <input type="date" class="form-control" id="id_reserved_date" name="reserved_date" value="{{ book.reserved_date|date:'Y-m-d' }}">
        </div>
        <div class="form-group form-check">
            {{ form_book.reserved }}
            <label class="form-check-label" for="id_reserved">Reserved</label>
        </div>
        <div class="form-group">
            {{ form_book.rating_average.label_tag }}
            <input type="text" class="form-control" id="id_rating_average" name="rating_average" required value="{{book.rating_average}}">
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock content %}

library/templates/editar_usuario.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Edit User</h2>
    <form method="post">
        {% csrf_token %}
        {{ formulario.as_p }}
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock content %}

library/templates/form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.title.label_tag }}
            <input type="text" class="form-control" id="id_title" name="title" required>
        </div>
        <div class="form-group">
            {{ form.author.label_tag }}
            <input type="text" class="form-control" id="id_author" name="author" required>
        </div>
        <div class="form-group">
            {{ form.description.label_tag }}
            <textarea class="form-control" id="id_description" name="description" rows="4" cols="50" required>{{ form.description.value }}</textarea>
        </div>
        <div class="form-group">
            {{ form.image.label_tag }}
            <input type="file" class="form-control-file" id="id_image" name="image" accept="image/*" required>
        </div>
        <div class="form-group">
            {{ form.reserved_date.label_tag }}
            <input type="date" class="form-control" id="id_reserved_date" name="reserved_date">
        </div>
        <div class="form-group form-check">
            {{ form.reserved }}
            <label class="form-check-label" for="id_reserved">Reserved</label>
        </div>
        <div class="form-group">
            {{ form.rating_average.label_tag }}
            <input type="text" class="form-control" id="id_rating_average" name="rating_average" required value=0>
        </div>
        
        <button type="submit" class="btn btn-primary">Add book</button>
    </form>
</div>
{% endblock content %}

library/templates/form_details.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form_details.isbn.label_tag }}
            <input type="text" class="form-control" id="id_isbn" name="isbn" required>   
        </div>
        <div class="form-group">
            {{ form_details.genre.label_tag }}
            <input type="text" class="form-control" id="id_genre" name="genre" required>   
        </div>
        <div class="form-group">
            {{ form_details.subject.label_tag }}
            <input type="text" class="form-control" id="id_subject" name="subject" required>   
        </div>
        <div class="form-group">
            {{ form_details.publisher.label_tag }}
            <input type="text" class="form-control" id="id_publisher" name="publisher" required>   
        </div>
        
        <button type="submit" class="btn btn-primary">Add book</button>
    </form>
</div>
{% endblock content %}